
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpjiwabalvczlwptuefv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwaml3YWJhbHZjemx3cHR1ZWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MzcwMjMsImV4cCI6MjA1NjQxMzAyM30.D1pgU6ORpo8IDyHk5IHh2rqf0UbEdA15A-g1mIZVwYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add a console log to verify the client is initialized correctly
console.log("Supabase client initialized with URL:", SUPABASE_URL);
